package com.p3.archon.dboperations.dbmodel.enums;

public enum DataAnalyticsJobStatus {
	TEST_CONNECTION_SCHEDULED, TEST_CONNECTION_INPROGRESS,TEST_CONNECTION_COMPLETED,TEST_CONNECTION_FAILED,
	ANALYSIS_SCHEDULED, ANALYSIS_INPROGRESS,ANALYSIS_COMPLETED,ANALYSIS_FAILED
}
