package com.p3.archon.dboperations.dbmodel.enums;

public enum ErtJobStatus {
	DRAFT,
	REVIEW,
	READY,
	PROCESSING,
	COMPLETED,
	FAILED,
	ANALYSING,
	ANALYSED,
	INGESTING_DATA,
	DATA_INGESTED,
	DELETING_DATA,
	DATA_DELETED,
	USER_CANCELLED,
	SCHEDULED_FOR_ANALYSYS,
	SCHEDULED_FOR_PROCESSING
}
