package com.p3.archon.dboperations.dbmodel.enums;

public enum FlatFileJobStatus {
	DRAFT, REVIEW, READY, PROCESSING, COMPLETED, FAILED, ANALYSING, ANALYSED, DATA_INGESTED, DELETING_DATA,
	USER_CANCELLED, SCHEDULED_FOR_ANALYSIS, SCHEDULED_FOR_PROCESSING, ANALYSIS_FAILED, ANALYSIS_COMPLETED
}
